# Favicon
favicon: /favicon.ico

# SEO
keywords: 

# Site title separator
separator: '-'

# RSS
rss: /atom.xml

# SNS config
sns:
  GitHub: //github.com/gitbruno
  RSS: /atom.xml

# Nav menu
menu:
  Home: /
  Archives: /archives

email: hello@brunoherfst.com
search: true

# Home config
#home:
#-
#  path: /
#  title: Books
#  desc: 
 
